apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ci-cd-deployment
  labels:
    app: flask-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-ci-cd
  template:
    metadata:
      labels:
        app: flask-ci-cd
    spec:
      containers:
        - name: flask-ci-cd-container
          image: flask-ci-cd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
