apiVersion: v1
kind: Service
metadata:
  name: flask-ci-cd-service
spec:
  type: NodePort
  selector:
    app: flask-ci-cd
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
